remote_theme: "mmistakes/minimal-mistakes"
title: "Jesse Geerts"
name: "Jesse Geerts"
description: "Jesse Geerts's personal website."
url: "https://jessegeerts.github.io"
repository: "jessegeerts/jessegeerts.github.io"
search: true

twitter:
  username: &twitter "jesse_geerts"


author:
  name   : &name "Jesse Geerts"
  avatar : "/assets/images/bio-photo.jpg"
  bio.   : "PhD student at University College London"
  github:  "jessegeerts"
  twitter: *twitter 
  email:   jessegeerts@gmail.com
  linkedin: https://www.linkedin.com/in/jesse-geerts-a4b923bb/

include: ["_pages"]

analytics:
  provider: "google"
  google:
    tracking_id: "UA-125348807-1"
    anonymize_ip: false # default
  
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache